import { Injectable, NotFoundException } from '@nestjs/common';
import { formatBudget } from '../common/utils/budget.util';
import { PrismaService } from '../prisma/prisma.service';
import PDFDocument from 'pdfkit';

@Injectable()
export class ScaleService {
  constructor(private readonly prisma: PrismaService) {}

  async findAll() {
    const contracts = await this.prisma.scaledContract.findMany({
      orderBy: { contractDate: 'desc' },
      include: {
        reviews: {
          select: {
            rating: true,
          },
        },
      },
    });

    return contracts.map((contract) => {
      const { reviews, ...rest } = contract;
      const reviewCount = reviews.length;
      const avgRating =
        reviewCount > 0
          ? Math.round(
              (reviews.reduce((sum, r) => sum + r.rating, 0) / reviewCount) * 10,
            ) / 10
          : 0;

      return {
        ...rest,
        pilotBudget: formatBudget(contract.pilotBudget),
        scaledBudget: formatBudget(contract.scaledBudget),
        avgRating,
        reviewCount,
      };
    });
  }

  // A small summary for the Trust/Outcomes dashboard — total pilots scaled
  // and combined contract value, computed from real records instead of
  // hardcoded stats.
  async summary() {
    const contracts = await this.findAll();

    return {
      totalScaled: contracts.length,
      contracts,
    };
  }

  /**
   * Generates a clean, one-page PDF document for a scaled contract.
   * Self-contained to allow easy testing and direct stream generation.
   */
  async generateContractPdf(id: string): Promise<Buffer> {
    const contract = await this.prisma.scaledContract.findUnique({
      where: { id },
    });

    if (!contract) {
      throw new NotFoundException(`Scaled contract with ID "${id}" not found`);
    }

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err: Error) => reject(err));

      // Header
      doc
        .fontSize(22)
        .font('Helvetica-Bold')
        .fillColor('#0284c7')
        .text('PilotGov', 50, 50);

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#64748b')
        .text('Public Sector Innovation & Pilot Scaling Platform', 50, 78);

      doc
        .fontSize(16)
        .font('Helvetica-Bold')
        .fillColor('#0f172a')
        .text('Procurement Contract', 50, 115);

      // Horizontal Rule
      doc
        .strokeColor('#e2e8f0')
        .lineWidth(1)
        .moveTo(50, 140)
        .lineTo(545, 140)
        .stroke();

      // Formatted Contract Date
      const formattedContractDate = new Date(
        contract.contractDate,
      ).toLocaleDateString('en-IN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      const fields: Array<{ label: string; value: string }> = [
        { label: 'Contract ID', value: contract.id },
        { label: 'Startup', value: contract.startup },
        { label: 'Department', value: contract.dept },
        { label: 'Title', value: contract.title },
        { label: 'Pilot Budget', value: formatBudget(contract.pilotBudget) },
        { label: 'Scaled Budget', value: formatBudget(contract.scaledBudget) },
        { label: 'Pilot Start Date', value: contract.pilotStartDate },
        { label: 'Contract Date', value: formattedContractDate },
      ];

      let currentY = 165;
      const labelX = 50;
      const valueX = 190;

      for (const field of fields) {
        doc
          .fontSize(11)
          .font('Helvetica-Bold')
          .fillColor('#475569')
          .text(field.label, labelX, currentY, { width: 130 });

        doc
          .fontSize(11)
          .font('Helvetica')
          .fillColor('#0f172a')
          .text(field.value || 'N/A', valueX, currentY, { width: 355 });

        currentY += 32;
      }

      // Divider before footer
      doc
        .strokeColor('#e2e8f0')
        .lineWidth(1)
        .moveTo(50, 730)
        .lineTo(545, 730)
        .stroke();

      // Footer
      const nowFormatted = new Date().toLocaleDateString('en-IN', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#94a3b8')
        .text(`Generated by PilotGov — ${nowFormatted}`, 50, 745, {
          align: 'center',
          width: 495,
        });

      doc.end();
    });
  }
}
